name: Life Check-in
description: Talk to the Personal Life Orchestrator
title: "[Life] Check-in"
labels: ["life-checkin"]
body:
  - type: input
    id: deadlines
    attributes:
      label: Non-movable deadlines (next 14 days)
      description: Number only
    validations:
      required: true
  
  - type: input
    id: domains
    attributes:
      label: Active high-load domains
      description: Number only
    validations:
      required: true
  
  - type: input
    id: energy
    attributes:
      label: Energy (1–5, comma-separated)
      placeholder: "2,3,2"
      description: Three energy scores from the last 3 days, comma-separated (e.g., "2,3,2")
    validations:
      required: true
  
  - type: textarea
    id: tasks
    attributes:
      label: Tasks / commitments
      description: Optional free text for future Planning Engine integration
    validations:
      required: false
